export const cities = [
    "Orașul Anenii Noi",
    "Orașul Balti",
    "Orașul Băsărăbeasca",
    "Orașul Biruința",
    "Orașul Briceni",
    "Orașul Bucovăț",
    "Orașul Cahul",
    "Orașul Căinari",
    "Orașul Călărași",
    "Orașul Camenca",
    "Orașul Cantemir",
    "Orașul Căușeni",
    "Orașul Ceadîr-Lunga",
    "Orașul Chișinău",
    "Orașul Cimișlia",
    "Orașul Codru",
    "Orașul Comrat",
    "Orașul Cornești",
    "Orașul Costești",
    "Orașul Crasnoe",
    "Orașul Cricova",
    "Orașul Criuleni",
    "Orașul Cupcini",
    "Orașul Dnestrovsc",
    "Orașul Dondușeni",
    "Orașul Drochia",
    "Orașul Dubăsari",
    "Orașul Durlești",
    "Orașul Edineț",
    "Orașul Fălești",
    "Orașul Florești",
    "Orașul Frunza",
    "Orașul Ghindesti",
    "Orașul Glodeni",
    "Orașul Grigoriopol",
    "Orașul Hincesti",
    "Orașul Ialoveni",
    "Orașul Iargara",
    "Orașul Leova",
    "Orașul Lipcani",
    "Orașul Maiac",
    "Orașul Marculesti",
    "Orașul Nisporeni",
    "Orașul Ocnita",
    "Orașul Orhei",
    "Orașul Otaci",
    "Orașul Rezina",
    "Orașul Ribnita",
    "Orașul Rîșcani",
    "Orașul Sîngera",
    "Orașul Sîngerei",
    "Orașul Slobozia",
    "Orașul Șoldănești",
    "Orașul Soroca",
    "Orașul Ștefan Vodă",
    "Orașul Strășeni",
    "Orașul Taraclia",
    "Orașul Telenești",
    "Orașul Tighina (Bender)",
    "Orașul Tiraspol",
    "Orașul Tiraspolul Nou",
    "Orașul Ungheni",
    "Orașul Vadul Lui Voda",
    "Orașul Vatra",
    "Orașul Vulcănești",
  ];
  